controllers/SignController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use app\modules\user\models\LoginForm;
use yii\web\Response;

class SignController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}
	
	/**
	 * @return string|Response
	 */
	public function actionLogin()
	{
		$model = new LoginForm();
		
		if($model->load(Yii::$app->request->post()) && $model->in()) {
			return $this->redirect(['/admin/dashboard/index']);
		}
		
		return $this->render('login', ['model' => $model]);
	}
	
	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();
		
		return $this->goHome();
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\kitchen\models\Ingridient;
use app\modules\kitchen\models\search\ProductSearch;

class SiteController extends Controller
{
	
	
	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}
	
	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		$searchModel = new ProductSearch();
		
		if(Yii::$app->request->isAjax && $searchModel->load(Yii::$app->request->get())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			
			return ActiveForm::validate($searchModel);
		}
		$dataProvider = $searchModel->searchFront(Yii::$app->request->queryParams);
		$ingridients = ArrayHelper::map(Ingridient::find()->asArray()->all(), 'id', 'name');
		
		return $this->render('index', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
			'ingridients'  => $ingridients,
		]);
	}
	
	
	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionAbout()
	{
		return $this->render('about');
	}
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use app\widgets\Alert;
use app\assets\AppAsset;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<?php $this->registerCsrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php

    NavBar::begin([
	    'brandLabel' => Yii::$app->user->isGuest ? Yii::$app->name : 'Вперед в админку',
	    'brandUrl'   => Yii::$app->user->isGuest ? Yii::$app->homeUrl : Url::toRoute(['/admin/dashboard/index']),
	    'options'    => [
		    'class' => 'navbar-inverse navbar-fixed-top',
	    ],
    ]);
    echo Nav::widget([
	    'options' => ['class' => 'navbar-nav navbar-right'],
	    'items'   => [
		    ['label' => 'Home', 'url' => ['/site/index']],
		    ['label' => 'About', 'url' => ['/site/about']],
		    Yii::$app->user->isGuest ? (
		    ['label' => 'Login', 'url' => ['/sign/login']]
		    ) : (
			    '<li>'
			    . Html::beginForm(['/sign/logout'], 'post')
			    . Html::submitButton(
				    'Logout (' . Yii::$app->user->identity->fullname . ')',
				    ['class' => 'btn btn-link logout']
			    )
			    . Html::endForm()
			    . '</li>'
		    ),
	    ],
    ]);
    NavBar::end();
    ?>

	<div class="container">
        <?= Breadcrumbs::widget([
	        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/sign/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>
	
        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
	
</div>

views/site/_product.php
<?php

use app\modules\kitchen\models\Product;

/**
 * @var $model Product
 */

?>

<div class="col-lg-4">
	<div class="bg-light">
                <h2><?= $model->name ?></h2>

                <p><?= $model->description ?></p>
				<div>
					                <img width="200px" height="200px" src="<?= $model->thumb ?>" alt="">
				</div>
		<?php if($model->rel): ?>
			<span>Количество совпадений:<?= $model->rel ?></span>
		<?php endif; ?>
            </div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';

use app\modules\kitchen\models\search\ProductSearch;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\widgets\ListView;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/**
 * @var $searchModel ProductSearch
 * @var $dataProvider ActiveDataProvider
 */
?>
<div class="site-index">
	
    <div class="jumbotron">
        <h1>Найти продукт</h1>
	    <?php $form = ActiveForm::begin(['method' => 'get', 'enableAjaxValidation' => true, 'action' => Url::toRoute(['/site/index'])]) ?>
	    <p class="lead">
	        <?= $form->field($searchModel, 'search')->widget(Select2::classname(), [
		        'data'              => $ingridients,
		        'maintainOrder'     => true,
		        'showToggleAll'     => false,
		        'toggleAllSettings' => [
			        'selectLabel'     => '<i class="fas fa-check-circle"></i> Выбрать все',
			        'unselectLabel'   => '<i class="fas fa-times-circle"></i> Отменить все',
			        'selectOptions'   => ['class' => 'text-success'],
			        'unselectOptions' => ['class' => 'text-danger'],
		        ],
		        'options'           => ['placeholder' => 'Выбирите ингридиенты', 'multiple' => true, 'value' => Yii::$app->request->get('ProductSearch')['search'] ?? []],
		        'pluginOptions'     => [
			        'allowClear'      => true,
			        'tags'            => true,
			        'tokenSeparators' => [',', ' '],
		        ],
		        'pluginEvents'      => [
		            'select2:select' => 'function() {
		                let li =$(".select2-selection__choice")
		               if(li.length > 5){
		               let i = 0
		               li.each(function(){
		               if(i === 0){
		          $(this).find(".select2-selection__choice__remove").trigger("click")
		               i++
		               }
		                     })
		               }
		              
		          	            }',
		        ],
	        ])->label(false); ?>
        </p>

        <p><button type="submit" class="btn btn-lg btn-success">Собрать</button></p>
	    <?php ActiveForm::end() ?>
    </div>

    <div class="body-content">

        <div class="row">
	          <?=
	          ListView::widget([
		          'dataProvider' => $dataProvider,
		          'summary'      => false,
		          'itemView'     => '_product',
		          'emptyText'    => 'Ничего не найдено',
	          ]);
	          ?>
        </div>

    </div>
	
</div>